/*****************************************************************************
 *  @file         logger.c
 *  @brief        Header file for Logger thread containing defines pertain-
 *                to logger.c.
 *  @Tools_Used   ARM-LINUX-GCC
 *  @Author(s)    Souvik De, Devansh Mittal
 *  @Date         March 16th, 2019
 *  @Modified     March 24th, 2019
 *  @version      1.1
*****************************************************************************/

#ifndef LOGGER_H
#define LOGGER_H

#include <stdio.h>
#include <sys/time.h>
#include<sys/syscall.h>

/* File pointer for the log file */
FILE *log_file_ptr;

/**
* @Brief  This function logs events, errors, and heartbeat notifications generated by the program
* @Param  (1) Dontes if file is to be oppened in W/R mode; (2) Log file path from command line
* @Return Error code
**/
int write_log(int IsFileCreated, char *LogFilePath);

#endif
